
tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python app.py migrate
    command: |
      python app.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

  - port: 5000
    visibility: public
    onOpen: open-preview
    
vscode:
  extensions:
    - ms-python.python